### ISSUE TITLE
Execução do projeto

### ISSUE THREAD

**Issue by mariojp** [DiegoAndradeD/CatalogoDeLivros#1]
Há algumas questões no projeto e no README que precisam ser abordadas. 

Solicitar a um outro membro da equipe que refaça a instalação e execução segundo o README:

É uma ótima ideia pedir a um colega de equipe que siga o README para instalar e executar o projeto. Isso ajudará a identificar quaisquer problemas que possam surgir durante o processo de configuração e a validar as instruções fornecidas.

Sugerir ao desenvolvedor fazer um fork do repositório:

Recomendo que você faça um fork do repositório original antes de realizar qualquer alteração. Isso permitirá que você tenha uma cópia separada para trabalhar sem afetar o repositório original. Você pode fazer isso executando o seguinte comando:

bash
Copy code
git clone https://github.com/seu-username/CatalogoDeLivros.git
Sobre a falta da pasta Frontend:

Parece que a pasta "Frontend" mencionada no README não existe no repositório. É importante verificar se a estrutura do projeto está correta. Se essa pasta não for necessária, é importante removê-la das instruções do README para evitar confusões.

Sobre as variáveis de ambiente ausentes:

As variáveis de ambiente são cruciais para a configuração correta do projeto, mas parece que os arquivos .env não foram incluídos no repositório, o que é uma prática comum para proteger informações confidenciais. No README, você deve orientar o desenvolvedor a criar esses arquivos e explicar como preenchê-los. Aqui está um exemplo de como isso pode ser abordado:

```markdown
### Configurando as Variáveis de Ambiente

Antes de executar o projeto, você precisará configurar algumas variáveis de ambiente. Siga estas etapas:

1. Crie um arquivo `.env` na raiz do projeto.

2. Preencha o arquivo `.env` com as seguintes variáveis e seus valores correspondentes:

API_KEY=chave_de_api_secreta
DATABASE_URL=url_do_banco_de_dados
OUTRA_VARIAVEL=valor_da_variavel

```

```javascript

Lembre-se de substituir `chave_de_api_secreta`, `url_do_banco_de_dados` e `valor_da_variavel` pelos valores apropriados.

3. Salve o arquivo `.env`.

Agora, as variáveis de ambiente estão configuradas e o projeto pode acessá-las durante a execução.

```

Sobre o erro de importação:

Você está enfrentando um erro de importação relacionado ao módulo auth.config nos arquivos auth.middleware.ts e auth.service.ts. Certifique-se de que o arquivo auth.config.ts existe no mesmo diretório desses arquivos e de que a importação esteja usando o caminho correto. Você também pode mencionar que a estrutura de diretórios deve corresponder ao que está definido no projeto.

Espero que essas sugestões ajudem a tornar o processo de instalação e execução do projeto mais suave. Lembre-se de que a documentação clara é fundamental para facilitar o desenvolvimento e a colaboração em equipe.

**Comment by DiegoAndradeD** [comment]
Desculpe a demora, os problemas relatados foram resolvidos e as instruções ausentes adicionadas.
